name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: echo "This step will execute when there is a push or PR"
  deploy-docs:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: deploy DG on any commit to master, to markbind.org/devdocs
        run: >-
          echo "This step will only execute when there is a push" &&
          echo ${{github.ref_type}}
      - name: deploy UG on release, to markbind.org
        if: github.ref_type == 'tag'
        run: >-
          echo "This step will only execute when there is a push + tag"